server:
  port: 8080 # ??????

spring:
  cassandra:
    contact-points: 127.0.0.1 # Cassandra ???????????????????
    port: 9042 # ???
    local-datacenter: datacenter1 # ???????????????????????
  ai:
    deepseek:
      api-key:  # ?? DeepSeek Api Key, ??????
      base-url: https://api.deepseek.com # DeepSeek ??? URL, ???????? api.deepseek.com
      chat:
        options:
          model: deepseek-chat  # ??????
          temperature: 0.8 # ???
    chat:
      memory:
        repository:
          cassandra:
            keyspace: ai_robot # 指定存储聊天记忆的 Keyspace（类似数据库名）
            table: t_ai_chat_memory # 表名
            time-to-live: 1095d # 数据的自动过期时间（1095天 ≈ 3年）
            initialize-schema: true  # 自动初始化表结构

    ollama:
      base-url: http://localhost:11434 # Ollama ???????, 11434 ??? Ollama ???????
      chat:
        options: # ????
          model: qwen3:14b # ?? Ollama ???????????????????????? 14b
          temperature: 0.7 # ???

    zhipuai:
      base-url: https://open.bigmodel.cn/api/paas # ?? AI ??? URL, ???????? open.bigmodel.cn/api/paas
      api-key:  # ???? AI ? API Key, ??????
      chat:
        options: # ????
          model: glm-4-air # ????????? AI ????
          temperature: 0.7 # ???

#    openai:
#      base-url: https://api.zhizengzeng.com/v1 # OpenAI ???????????????????????
#      api-key:   # ?????? API Key, ??????
#      chat:
#        options:
#          model: gpt-4o # ????
#          temperature: 0.7 # ???

    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # OpenAI ???????????????????
      api-key:   # ???????? API Key, ??????
      chat:
        options:
          model: qwen-omni-turbo # ????
          temperature: 0.7 # ???

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
